### ISSUE TITLE
Issues with Digital Miner

### ISSUE THREAD

**Issue by oryfoxer7410** [oryfoxer7410/1.10.2-Pack#19]
Digital Miner seems to disappear until you place a block ontop of its location.

**Comment by oryfoxer7410** [comment]
https://github.com/aidancbrady/Mekanism/issues/4114

**Comment by orjanj5** [comment]
Digital miner removes vinteum ores, but the vinteum from the ores seems to dissapear

**Comment by oryfoxer7410** [comment]
believe server related issue. Marking as closed.
