### ISSUE TITLE
Issue with ProjectE & Refined Storage in Tranmutation Table

### ISSUE THREAD

**Issue by oryfoxer7410** [oryfoxer7410/1.10.2-Pack#20]
Causes disconnect, a wait and reconnect fixes the issue.

**Comment by oryfoxer7410** [comment]
https://github.com/sinkillerj/ProjectE/issues/1466

Opened Issue

**Comment by oryfoxer7410** [comment]
May Remove EMC values if unable to get quick update.

**Comment by orjanj5** [comment]
Trying to pull a 1k storage disk out of a transmutation tablet will either give u nothing by just flashing the icon centered on the cursor or crash the game. Just tested within single player, put 2 into the tablet, could take 2 out, but not any more. In my case the icon just flashed under the cursor.

**Comment by oryfoxer7410** [comment]
could be serverside issue, need to confirm on new server and in single player.
