### ISSUE TITLE
Draconic Evolution mob grinder stuck on morph ghosts

### ISSUE THREAD

**Issue by Teraku** [oryfoxer7410/1.10.2-Pack#32]
Whenever the Mob Grinder from Draconic Evolution kills something, the killed enemy leaves a ghost behind (from Metamorph). However, this causes the mob grinder to become stuck and not kill anything until the mob ghosts are gone.

**Comment by oryfoxer7410** [comment]
I will take a look into this. I will see if there is a bypass for "fake" players. Will update shortly. Thanks for the report.

**Comment by oryfoxer7410** [comment]
https://github.com/mchorse/metamorph/issues/9

**Comment by oryfoxer7410** [comment]
Added Pre-Release build of MetaMorph into 0.1.7.2.3 (current Latest). Testing fix for ghosts on Fake Players

**Comment by oryfoxer7410** [comment]
removed morph. pre-release references SP
