### ISSUE TITLE
[Server] Quantum Quarry Server Crash

### ISSUE THREAD

**Issue by zourath** [oryfoxer7410/1.10.2-Pack#35]
The ExtraUtils2 Quantum Quarry appears to crash the server when it runs, so now I crash the server on login.

**Comment by oryfoxer7410** [comment]
Can you upload your crash log to https://hastebin.com/ and post here

**Comment by oryfoxer7410** [comment]
I see, you were talking about the official server, this is a sponge issue. I am looking into it. Thanks for the report. Will update when resolved.

**Comment by zourath** [comment]
https://hastebin.com/ilirodakah.sql

The only crash log I have from today, I suspect this isn't actually helpful though. It's a problem that's crashing the server, it's not a client crash at all.

**Comment by oryfoxer7410** [comment]
Ok, it should be fixed.

**Comment by oryfoxer7410** [comment]
The server is rebooting, can you join to see if your quarry works? It's Sponge related.

**Comment by zourath** [comment]
Looks like it's still crashing.

**Comment by oryfoxer7410** [comment]
Last Reboot

**Comment by oryfoxer7410** [comment]
If you could logon for me after it boots, if not, I will have to remove your playerdata.

**Comment by oryfoxer7410** [comment]
Almost back up.

**Comment by zourath** [comment]
Still crashing, although I got much further than last time. Stuff was actually happening for a bit.

**Comment by oryfoxer7410** [comment]
:^) I see you are on now
