### ISSUE TITLE
Meta-Morph Removal

### ISSUE THREAD

**Issue by oryfoxer7410** [oryfoxer7410/1.10.2-Pack#52]
Remove Meta-Morph? Not sure, seems not worth it and its bugs for little benefit. Probably worth wait for iChun.

**Comment by kirashi3** [comment]
I'd support this removal, even without iChun's Morph mod being ready. Morphing has caused random client disconnects and a couple complete client crashes for some players on my home server. (Not a big deal; I simply told them to stop morphing for their sanity. :D )

**Comment by oryfoxer7410** [comment]
removed.
