### ISSUE TITLE
Remove TechReborn

### ISSUE THREAD

**Issue by oryfoxer7410** [oryfoxer7410/1.10.2-Pack#59]
debating.

**Comment by kirashi3** [comment]
I too was debating asking this very question... Although TechReborn adds a bit to IC2 and GregTech, I don't find the TechReborn/Biomes'O Plenty Peridot, Ruby, or Sapphire as useful or functional as ProjectRed's versions of the same materials.

#####FruitBasket and I are OK with seeing TechRebord go.

(Sadly, ProjectRed does not yet support 1.10.2, so we'll just have to wait for that...)
