### ISSUE TITLE
Yellorium when smelted turns into Uranium

### ISSUE THREAD

**Issue by LordDew** [oryfoxer7410/1.10.2-Pack#6]
When yellorium is smelted, the product becomes Uranium from Mystical Crops.
![2016-12-26_15 59 24](https://cloud.githubusercontent.com/assets/24782558/21486993/679815e4-cb84-11e6-9f6e-631eb766cf8d.png)

**Comment by oryfoxer7410** [comment]
Will look into the issue. I think I know the cause.

**Comment by oryfoxer7410** [comment]
This is unidictionary unifying ores and its supposed to happen. As long as Reactors are not having issues with the uranium, then I will leave it there. The type is not radioactive.
