### ISSUE TITLE
[Bug] IC2 Neutron Relfector

### ISSUE THREAD

**Issue by ContainedShadow** [oryfoxer7410/1.10.2-Pack#67]
When trying to craft a neutron reflector it gives you the TechReborn one and this cannot be used for any recipe that is not from TechReborn.
![image](https://cloud.githubusercontent.com/assets/25088716/22256989/bb195950-e25c-11e6-8e6d-2fd1b862a108.png)

**Comment by oryfoxer7410** [comment]
Fixed. You will notice now all copper will default to IC2 over Substratum in production. You will initially have duplicates until all substratum in inventory is used.
