### ISSUE TITLE
[Bug] Recipi TechReborne

### ISSUE THREAD

**Issue by ContainedShadow** [oryfoxer7410/1.10.2-Pack#68]
The industrial electrolyzer has a recipe that needs 18 empty cells from TechReborn. But the cells only stack to 16. 
![image](https://cloud.githubusercontent.com/assets/25088716/22346922/2f648dd4-e406-11e6-8ab9-d621fb8c9548.png)
![image](https://cloud.githubusercontent.com/assets/25088716/22346953/4cec4158-e406-11e6-97b5-dd0e66aab682.png)

**Comment by oryfoxer7410** [comment]
TechReborn is removed in next release.
