### ISSUE TITLE
[Bug] levels don't load

### ISSUE THREAD

**Issue by 0Nomad** [oryfoxer7410/1.10.2-Pack#69]
it gets stuck on"building terrain" and it goes on forever

edit:

"superflat", and "realistic" worlds loads fine
but default worlds do not

My Specs

![calispecs](https://cloud.githubusercontent.com/assets/25396692/22392925/56a308c6-e4c4-11e6-88fd-4ae7ee673e45.JPG)

**Comment by oryfoxer7410** [comment]
Issues confirmed. Will be fixed in next release.
