### ISSUE TITLE
[Suggestion] Flux Network

### ISSUE THREAD

**Issue by orjanj5** [oryfoxer7410/1.10.2-Pack#71]
Allows to teleport items and rf as the tesseracts do but with different blocks

**Comment by oryfoxer7410** [comment]
What about quantumentanglopers and dimensional transceivers? Do we need another tesseract replacement?

**Comment by orjanj5** [comment]
The reason i want it is because it is a lot easier to make compared to those two, and i had the name wrong but i fixed it

**Comment by oryfoxer7410** [comment]
I will look into it.

**Comment by orjanj5** [comment]
ok

**Comment by oryfoxer7410** [comment]
Requires Telsa API right now. Will have to do some testing

**Comment by oryfoxer7410** [comment]
closed due to cofh being released. Will wait for tesseracts.
