### ISSUE TITLE
[Suggestion] Block Drops

### ISSUE THREAD

**Issue by oryfoxer7410** [oryfoxer7410/1.10.2-Pack#73]
https://minecraft.curseforge.com/projects/block-drops-jei-addon

**Comment by xcb567** [comment]
* Change the config settings, default missed at least dense ores drops for me.
 "allDrops" to true
 "iteration=9999" (higher value makes no difference currently)

* Pregenerate both .key files since its real slow generating them the first time.

**Comment by oryfoxer7410** [comment]
added. and pregened.
