### ISSUE TITLE
[BUG] IC2 Glass fibre cables

### ISSUE THREAD

**Issue by ContainedShadow** [oryfoxer7410/1.10.2-Pack#74]
The IC2 Glass Fibre cables explode when you use them with a quantum solar panel or a mekansim induction matrix. They are supposed to be the highest tier cable and i don't think that they should explode.

**Comment by oryfoxer7410** [comment]
How much power are you pushing through the cable? IC2 cables will explode if over powered. If its a bug in IC2, I can disabled explosions.

**Comment by ContainedShadow** [comment]
I'm sending more over the cable that it can handle but I just disapears in thin air and leaves a small trail behind. I don't think this should be a problem. I played with those on a nother server and I sended over 1mil eu through them without exploding.

**Comment by ContainedShadow** [comment]
So with what you are saying, the quantum solar panel outputs 2048 eu/t, I can't hook up more then 4 panels to one single kabel or else the whole line will explode?  Thats seems a bit odd no. Also the solar panels already have a drawback. They produce double the output amount at day and 2048 eu/t at night.
